# Generated by Django 5.0.6 on 2024-08-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_usernamepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernamepassword',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usernamepassword',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usernamepassword',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usernamepassword',
            name='pin',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usernamepassword',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
