# Generated by Django 5.0.6 on 2024-08-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_usernamepassword_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernamepassword',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usernamepassword',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usernamepassword',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usernamepassword',
            name='pin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usernamepassword',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
